defer: inline fragment warning
apollographql/apollo-ios pull request #3159
Opened 2023-07-28 20:48 UTC by BobaFetters

-Adding validation error to graphql-js for deferred inline fragments with no type condition

Closes #3158

2023-07-28 21:38 UTC, AnthonyMDev approved these changes
This looks great! Nice job, and so quick!

2023-07-28 21:56 UTC, calvincestari requested changes
I've left a couple suggestions, looks good though.

2023-07-28 21:56 UTC, calvincestari commented on Sources/ApolloCodegenLib/Frontend/JavaScript/src/__tests__/deferCompilationTests.ts
> +  describe("query has inline fragment with @defer directive and no type condition should throw error", () => {
```suggestion
  describe("query has inline fragment with @defer directive and no type condition", () => {
```

2023-07-28 21:56 UTC, calvincestari commented on Sources/ApolloCodegenLib/Frontend/JavaScript/src/__tests__/deferCompilationTests.ts
> +    it("should compile inline fragment with directive", () => {
```suggestion
    it(" should throw error", () => {
```

2023-07-28 21:56 UTC, calvincestari commented on Sources/ApolloCodegenLib/Frontend/JavaScript/src/__tests__/deferCompilationTests.ts
> +  describe("query has inline fragment with @defer directive should not throw error", () => {
I believe this case is already covered by the test up on [line 37](https://github.com/apollographql/apollo-ios/pull/3159/files#diff-9764f88416cc3dd09bf331172384c2bb39d377cf1547465df39e49755aad50c6R37). Can remove this as a duplicate unless I'm missing something here.

2023-07-28 21:56 UTC, calvincestari commented on Sources/ApolloCodegenLib/Frontend/JavaScript/src/validationRules.ts
> +          if (directive.name.value == "defer" && node.typeCondition == undefined) {
`"defer"` should already be available in `GraphQLDeferDirective.name`. Probably be better to use that than duplicate strings.

2023-07-31 17:09 UTC, calvincestari approved these changes

2023-07-31 17:11 UTC, calvincestari commented
Thanks @BobaFetters!

2023-07-31 19:03 UTC, merged