feature: final graphql operation definitions
apollographql/apollo-ios pull request #3189
Opened 2023-08-12 00:53 UTC by Mordil

Re-adds generated GraphQL operations to be marked as `final` through a new `OutputOptions` property: `finalOperationDefinitions`.

This is to support fixing this in a backwards-compatible way, and still allowing people control over how they use the generated operation models.

This resolves #3183

2023-08-15 20:52 UTC, AnthonyMDev requested changes
Thanks so much for working on this! Implementation looks spot on to me! Just a couple things to consider.

- We need to add the new option to the documentation of the CLI

- I think we should also add the `final` keyword to local cache mutations if this option is `true`. That would be done in the `LocalCacheMutationDefinitionTemplate`.

- @BobaFetters what do you think of the naming of this configuration option? I'm not coming up with a better name off the top of my head right now, but I feel like it's not clear what `finalOperationDefinitions` means without having to read the docs.

2023-08-16 00:56 UTC, Mordil commented
I just came up with `markClassesAsFinal`, but now I'm wondering if that name now pushes is so we should mark `Mock` definitions as `final` as well?

It'd probably be easier to make it so that it applies to _all_ classes to start with, and if people say they want more granular control, later the options are split into further sub-options

2023-08-17 17:12 UTC, Mordil commented
> Overall I think this looks great, thanks for taking this on!
> 
> As for naming, since the `final` keyword is a modifier thoughts on naming the option something like `applyFinalModifier`?

I don't have a strong preference. It's what y'all think is best.

2023-08-18 13:42 UTC, BobaFetters commented
> > Overall I think this looks great, thanks for taking this on!
> > As for naming, since the `final` keyword is a modifier thoughts on naming the option something like `applyFinalModifier`?
> 
> I don't have a strong preference. It's what y'all think is best.

@AnthonyMDev thoughts?

2023-08-28 20:13 UTC, calvincestari commented
> I just came up with `markClassesAsFinal`, but now I'm wondering if that name now pushes is so we should mark `Mock` definitions as `final` as well?

I'm less inclined to want `final` mock classes. I think the fact that they're intended to be test classes should allow for more complicated, do-as-you-want code.

> It'd probably be easier to make it so that it applies to _all_ classes to start with, and if people say they want more granular control, later the options are split into further sub-options

Yes I agree.

I'm happy with the config option named `markClassesAsFinal`, I think it's descriptive enough.

2023-09-01 19:49 UTC, Mordil commented
> I felt like `finalOperationDefinitions` wasn't completely clear about what `final` meant in the context. But now `markClassesAsFinal` makes me confused about what `Classes` means. I don't think people using the codegen really know exactly what it is we are generating as classes vs structs.
> 
> What about `markOperationDefinitionsAsFinal`? I think that covers all our bases.
> 
> And I agree with @calvincestari that mocks should not be `final`.

Again, I have zero preferences.

I'll update the PR with this new proposed name, at the same time that I'll squash the commits and update with the latest version of the dev branch.

Appreciate the feedback!

2023-09-05 22:15 UTC, AnthonyMDev approved these changes

2023-09-05 22:15 UTC, AnthonyMDev commented
Thanks so much for this @Mordil! This looks great! Merging this in now, we'll get it out in the next release!

2023-09-05 22:15 UTC, merged